#!/bin/sh
#
# bspwm config

# desktops
bspc monitor -d I II III IV V VI VII VIII IX X

# border
bspc config border_width 2
bspc config window_gap 16

bspc config borderless_monocle false
bspc config gapless_monocle false

bspc config normal_border_color "#$THEME_CS_DARK_GREY"
bspc config active_border_color "#$THEME_CS_DARK_GREY"
bspc config focused_border_color "#$THEME_CS_YELLOW"
bspc config presel_feedback_color "#$THEME_CS_YELLOW"

# windowing
bspc config split_ratio 0.5

# mouse
bspc config pointer_modifier mod1
bspc config pointer_motion_interval 0

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false

# rules
bspc rule -a feh state=floating
bspc rule -a "*:zathura" state=tiled
